kind: pipeline
type: docker
name: default

steps:
- name: installation
  image: python
  commands:
  - pip install Flask
  - pip install requests

- name: hello
  image: python
  commands:
  - python ./hello.py

- name: testing
  image: python
  commands:
  - python --version

- name: fascade
  image: python
  commands:
  - pip install requests
  - pip install Flask
  - python ./fascade.py

- name: logging
  image: python
  commands:
  - pip install requests
  - python ./log_srv.py
  - pip install Flask

- name: msg
  image: python
  commands:
  - pip install requests
  - python ./msg-srv.py
  - pip install Flask

